# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nome',
            field=models.CharField(default='Nome', max_length=30),
            preserve_default=False,
        ),
    ]
